### ISSUE TITLE
Unable to fetch Binance tickers. Error =  'float' object has no attribute 'encode'

### ISSUE THREAD

**Issue by Valentino2008** [Fluronix/Cefi-triangular-arbitrage-bot#1]
When I run the main.py I get the error "Unable to fetch Binance tickers. Error = 'float' object has no attribute 'encode'" someone knows how to fix it?

**Comment by algoclient** [comment]
Hi @Valentino2008  the error might be because you didn’t input your API key on the bot_settings.xlsx

**Comment by Valentino2008** [comment]
Thanks for responding, and I inserted my api keys, but it seems to me that the error is being caused because my telegram id appears in decimals, even though I write them without

**Comment by Valentino2008** [comment]
thank you very much, now I am having this error: 

Unable to fetch Binance tickers. Error = (400, -1022, 'Signature for this request is not valid.', {'Content-Type': 'application/json', 'Content-Length': '63', 'Connection': 'keep-alive ', 'Date': 'Sat, 22 Jun 2024 19:45:16 GMT', 'Server': 'nginx', 'Strict-Transport-Security': 'max-age=31536000; -Options': 'SAMEORIGIN', 'X-Xss-Protection': '1; mode=block', 'X-Content-Type-Options': 'nosniff', 'Content-Security-Policy': "default-src 'self'", 'X-Content-Security-Policy': "default-src 'self'", 'X-WebKit-CSP': "default-src 'self'", 'Cache-Control': 'no- cache, no-store, must-revalidate', 'Pragma': 'no-cache', 'Expires': '0', 'X-Cache': 'Error from cloudfront', 'Via': '1.1 5d9a524e4aca6aab7126483cd2dfb87a.cloudfront .net (CloudFront)', 'X-Amz-Cf-Pop': 'EZE50-P1', 'X-Amz-Cf-Id': 'JV29T4KjiBvIbcwo65mWCuPUviAhaF2CEwvYCiJesdsuC4NVyf8dVw=='}, None)

**Comment by Valentino2008** [comment]
Thanks you

**Comment by Valentino2008** [comment]
I have another issue the bot is making a loop: Finding Arbitrage... 1
Error on while loop float expected at most 1 argument, got 2
Finding Arbitrage... 1
Error on while loop float expected at most 1 argument, got 2
Finding Arbitrage... 1
Error on while loop float expected at most 1 argument, got 2
Finding Arbitrage... 1
Error on while loop float expected at most 1 argument, got 2
Finding Arbitrage... 1
Error on while loop float expected at most 1 argument, got 2
Finding Arbitrage... 1
Error on while loop float expected at most 1 argument, got 2
Finding Arbitrage... 1
Error on while loop float expected at most 1 argument, got 2
Finding Arbitrage... 1
Error on while loop float expected at most 1 argument, got 2
Finding Arbitrage... 1
Error on while loop float expected at most 1 argument, got 2
Finding Arbitrage... 1
Error on while loop float expected at most 1 argument, got 2
Finding Arbitrage... 1
Error on while loop float expected at most 1 argument, got 2
Finding Arbitrage... 1
Error on while loop float expected at most 1 argument, got 2
Finding Arbitrage... 1
Error on while loop float expected at most 1 argument, got 2
Finding Arbitrage... 1
Error on while loop float expected at most 1 argument, got 2
Finding Arbitrage... 1
Error on while loop float expected at most 1 argument, got 2
Finding Arbitrage... 1
Error on while loop float expected at most 1 argument, got 2

**Comment by algoclient** [comment]
> I have another issue the bot is making a loop: Finding Arbitrage... 1 Error on while loop float expected at most 1 argument, got 2 Finding Arbitrage... 1 Error on while loop float expected at most 1 argument, got 2 Finding Arbitrage... 1 Error on while loop float expected at most 1 argument, got 2 Finding Arbitrage... 1 Error on while loop float expected at most 1 argument, got 2 Finding Arbitrage... 1 Error on while loop float expected at most 1 argument, got 2 Finding Arbitrage... 1 Error on while loop float expected at most 1 argument, got 2 Finding Arbitrage... 1 Error on while loop float expected at most 1 argument, got 2 Finding Arbitrage... 1 Error on while loop float expected at most 1 argument, got 2 Finding Arbitrage... 1 Error on while loop float expected at most 1 argument, got 2 Finding Arbitrage... 1 Error on while loop float expected at most 1 argument, got 2 Finding Arbitrage... 1 Error on while loop float expected at most 1 argument, got 2 Finding Arbitrage... 1 Error on while loop float expected at most 1 argument, got 2 Finding Arbitrage... 1 Error on while loop float expected at most 1 argument, got 2 Finding Arbitrage... 1 Error on while loop float expected at most 1 argument, got 2 Finding Arbitrage... 1 Error on while loop float expected at most 1 argument, got 2 Finding Arbitrage... 1 Error on while loop float expected at most 1 argument, got 2

Run the stream file

**Comment by Valentino2008** [comment]
I did it but the error still persists

**Comment by Valentino2008** [comment]
I did it but the error continues

**Comment by Valentino2008** [comment]
I had solve the error, thanks.

**Comment by Valentino2008** [comment]
Hello, the bot is in a loop and it is not making some arbritraje: Finding Arbitrage... 4
Finding Arbitrage... 5
Finding Arbitrage... 6
Finding Arbitrage... 7
Finding Arbitrage... 8
Finding Arbitrage... 9
Finding Arbitrage... 10
Finding Arbitrage... 11
Finding Arbitrage... 12
Finding Arbitrage... 13
Finding Arbitrage... 14
Finding Arbitrage... 15
Finding Arbitrage... 16
Finding Arbitrage... 17
Finding Arbitrage... 18
Finding Arbitrage... 19
Finding Arbitrage... 20
Finding Arbitrage... 21
Finding Arbitrage... 22
Finding Arbitrage... 23
Finding Arbitrage... 24
Finding Arbitrage... 25
Finding Arbitrage... 26
Finding Arbitrage... 27
Finding Arbitrage... 28
Finding Arbitrage... 29
Finding Arbitrage... 30
Finding Arbitrage... 31
Finding Arbitrage... 32
Finding Arbitrage... 33
Finding Arbitrage... 34
Finding Arbitrage... 35
Finding Arbitrage... 36
Finding Arbitrage... 37
Finding Arbitrage... 38
Finding Arbitrage... 39
Finding Arbitrage... 40
Finding Arbitrage... 41
Finding Arbitrage... 42
Finding Arbitrage... 43
Finding Arbitrage... 44
Finding Arbitrage... 45
Finding Arbitrage... 46
Finding Arbitrage... 47
Finding Arbitrage... 48
Finding Arbitrage... 49
Finding Arbitrage... 50
Finding Arbitrage... 51
Finding Arbitrage... 52
Finding Arbitrage... 53
Finding Arbitrage... 54
Finding Arbitrage... 55
Finding Arbitrage... 56
Finding Arbitrage... 57
Finding Arbitrage... 58
Finding Arbitrage... 59
Finding Arbitrage... 60
Finding Arbitrage... 61
Finding Arbitrage... 62
Finding Arbitrage... 63
Finding Arbitrage... 64
Finding Arbitrage... 65
Finding Arbitrage... 66
Finding Arbitrage... 67
Finding Arbitrage... 68
Finding Arbitrage... 69
Finding Arbitrage... 70
Finding Arbitrage... 71
Finding Arbitrage... 72
Finding Arbitrage... 73
Finding Arbitrage... 74
Finding Arbitrage... 75
Finding Arbitrage... 76
Finding Arbitrage... 77
Finding Arbitrage... 78
Finding Arbitrage... 79
Finding Arbitrage... 80
Finding Arbitrage... 81
Finding Arbitrage... 82
Finding Arbitrage... 83
Finding Arbitrage... 84
Finding Arbitrage... 85
Finding Arbitrage... 86
Finding Arbitrage... 87
Finding Arbitrage... 88
Finding Arbitrage... 89
Finding Arbitrage... 90
Finding Arbitrage... 91
Finding Arbitrage... 92
Finding Arbitrage... 93
Finding Arbitrage... 94
Finding Arbitrage... 95
Finding Arbitrage... 96
Finding Arbitrage... 97
Finding Arbitrage... 98
Finding Arbitrage... 99
Finding Arbitrage... 100
Finding Arbitrage... 101
Finding Arbitrage... 102
Finding Arbitrage... 103
Finding Arbitrage... 104
Finding Arbitrage... 105
Finding Arbitrage... 106
Finding Arbitrage... 107
Finding Arbitrage... 108
Finding Arbitrage... 109
Finding Arbitrage... 110
Finding Arbitrage... 111
Finding Arbitrage... 112
Finding Arbitrage... 113
Finding Arbitrage... 114
Finding Arbitrage... 115

**Comment by algoclient** [comment]
bot working now
